# Generated by Django 4.2.1 on 2023-05-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cat', models.IntegerField()),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('eimage', models.ImageField(upload_to='Image')),
            ],
        ),
    ]
