# Generated by Django 4.2.1 on 2023-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Historical'), (2, 'Biography'), (3, 'Cook'), (4, 'Poetry')], verbose_name='Books Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Book Price'),
        ),
    ]
