# Generated by Django 4.2.1 on 2023-05-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapp', '0002_alter_product_cat_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Historical'), (2, 'Biography'), (3, 'Cook'), (4, 'Poetry')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Book Name'),
        ),
    ]
